swagger: '2.0'
info:
  version: "0.0.1"
  title: <IMG SRC=x onerror="alert(String.fromCharCode(88,83,83))">
  description: <IMG SRC=x onerror="alert(String.fromCharCode(88,83,83))">
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
